name: CI

# on:
#   push:
#     branches:
#       - main
on: workflow_dispatch

jobs:
  inflate:
    name: Infate `*.netkan` files
    runs-on: windows-latest
    permissions:
      contents: write
      # id-token: write
    concurrency: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Inflate each `*.netkan` file
        run: |
          $netkan_path = Resolve-Path "./.netkan/windows/netkan.exe"
          echo "variable `$netkan_path: $($netkan_path)";
          Set-Alias -Name netkan.exe -Value $netkan_path
          $env:PATH += $netkan_path
          foreach `
            ($elem in gci -File -Path .\ -Recurse -Filter *.netkan){
              Push-Location -Path (get-item $elem).Directory;
              echo "cwd: $(Get-Location)";
              netkan.exe --verbose $elem --github-token $env:GITHUB_TOKEN
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit inflated `*.ckan` files
        # https://stackoverflow.com/questions/57921401/push-to-origin-from-github-action/58393457#58393457
        # https://github.com/actions/checkout/pull/1707
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email ${{ github.actor_id }}+github-actions[bot]@users.noreply.github.com
          git fetch
          git checkout main
          git checkout ckan/inflated
          git merge -m "Merge branch 'main' into 'ckan/inflated'" main
          git add -A
          git commit -am "Automated generation of .ckan files"
          git checkout main
          git merge -m "Merge branch 'ckan/inflated' into 'main'" ckan/inflated
          git push
